baseURL = "https://affectionate-pasteur-c40212.netlify.com"
languageCode = "ru-ru"
title = "Furnitura67 | От доводчика до ручки"
theme = "bootstrap"

defaultContentLanguage = "ru"
disableHugoGeneratorInject = false
# enableGitInfo = true

enableRobotsTXT = true
# google analytics tracking id
# googleAnalytics = ""

disableKinds = ["taxonomy", "taxonomyTerm"]

# Параметры (логотип можно создать здесь http://logoza.ru/app/)
# Эффекты - http://nisnom.com/category/veb-razrabotki/
# Шрифты - https://fonts.google.com
[params]
    logo = "images/logo.png"
    email = "temp@mail.ru" # адрес, на которые будут приходить сообщения с сайта
    defaultKeywords = ["furnitura67", "furniture", "фурнитура67", "фурнитура"]
    defaultDescription = "Furnitura67 | От доводчика до ручки"
    # Format dates with Go's time formatting
    dateFormat = "January 2, 2006"

# Site Menus
[menu]
   # Navbar Menus
   [[menu.main]]
      name    = "Главная"
      url     = "/"
      weight  = 1
    [[menu.main]]
      name    = "Акции и новости"
      url     = "/promo/"
      weight  = 2
    [[menu.main]]
      name    = "Контакты"
      url     = "/contact/"
      weight  = 3