backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Настройки"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: benefit
        label: Benefit
        file: site/data/benefit.toml
        description: Наши преимущества
        fields:
          - name: benefit
            label: Benefit
            widget: list
            fields:
              - {label: Функционал используется, name: enabled , widget: boolean}
              - {label: Верхний заголовок раздела, name: topTitle, widget: string}
              - {label: Основной заголовок раздела, name: title, widget: string}
              - {label: Нижний заголовок раздела, name: subTitle, widget: text}
